{
  "id": "CVE-2025-29294",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2025-03-24T16:15:56.460",
  "lastModified": "2025-03-24T17:15:20.880",
  "vulnStatus": "Rejected",
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "Rejected reason: DO NOT USE THIS CVE RECORD. ConsultIDs: none. Reason: This record was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: none."
    }
  ],
  "metrics": {},
  "references": []
}