{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2025-2853",
      "ASSIGNER": "cve@gitlab.com"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-770"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/527218",
          "name": "GitLab Issue #527218",
          "refsource": "",
          "tags": []
        },
        {
          "url": "https://hackerone.com/reports/3015673",
          "name": "HackerOne Bug Bounty Report #3015673",
          "refsource": "",
          "tags": []
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An issue has been discovered in GitLab CE/EE affecting all versions before 17.10.7, 17.11 before 17.11.3, and 18.0 before 18.0.1. A lack of proper validation in GitLab could allow an authenticated user to cause a denial of service condition."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "impact": {},
  "publishedDate": "2025-05-22T14:16Z",
  "lastModifiedDate": "2025-05-22T14:16Z"
}