{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2020-28163",
      "ASSIGNER": "cve@mitre.org"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2026000",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=2026000",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://www.prevanders.net/dwarfbug.html#DW202010-003",
          "name": "https://www.prevanders.net/dwarfbug.html#DW202010-003",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "http://web.archive.org/web/20190601140703/https://sourceforge.net/projects/libdwarf/",
          "name": "http://web.archive.org/web/20190601140703/https://sourceforge.net/projects/libdwarf/",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/davea42/libdwarf-code/commit/faf99408e3f9f706fc3809dd400e831f989778d3",
          "name": "https://github.com/davea42/libdwarf-code/commit/faf99408e3f9f706fc3809dd400e831f989778d3",
          "refsource": "MISC",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "libdwarf before 20201201 allows a dwarf_print_lines.c NULL pointer dereference and application crash via a DWARF5 line-table header that has an invalid FORM for a pathname."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2023-04-16T00:15Z",
  "lastModifiedDate": "2023-04-17T13:12Z"
}