{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2024-8041",
      "ASSIGNER": "cve@gitlab.com"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/463092",
          "name": "GitLab Issue #463092",
          "refsource": "",
          "tags": [

          ]
        },
        {
          "url": "https://hackerone.com/reports/2499070",
          "name": "HackerOne Bug Bounty Report #2499070",
          "refsource": "",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A Denial of Service (DoS) issue has been discovered in GitLab CE/EE affecting all versions prior to 17.1.6, 17.2 prior to 17.2.4, and 17.3 prior to 17.3.1. A denial of service could occur upon importing a maliciously crafted repository using the GitHub importer."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2024-08-22T16:15Z",
  "lastModifiedDate": "2024-08-23T16:18Z"
}